CC = gcc
CFLAGS = -std=c99 -Wall -pedantic
#CFLAGS = -std=c99 

default: L4T5

all: L4T1 L4T2 L4T3 L4T4 L4T5 

L4T1: L4T1.c
	$(CC) -o L4T1 L4T1.c $(CFLAGS)

L4T2: L4T2.c
	$(CC) -o L4T2 L4T2.c $(CFLAGS)

L4T3: L4T3.c
	$(CC) -o L4T3 L4T3.c $(CFLAGS)

L4T4: L4T4.c
	$(CC) -o L4T4 L4T4.c $(CFLAGS)

L4T5: L4T5.c
	$(CC) -o L4T5 L4T5.c $(CFLAGS)

clean:
	rm -rfv L4T1 L4T2 L4T3 L4T4 L4T5
