CC = gcc
CFLAGS = -std=c99 -Wall

default: L3T4

all: L3T1 L3T2 L3T3 L3T4 L3T5 

L3T1: L3T1.c
	$(CC) -o L3T1 L3T1.c $(CFLAGS)

L3T2: L3T2.c
	$(CC) -o L3T2 L3T2.c $(CFLAGS)

L3T3: L3T3.c
	$(CC) -o L3T3 L3T3.c $(CFLAGS)

L3T4: L3T4.c
	$(CC) -o L3T4 L3T4.c $(CFLAGS)

L3T5: L3T5.c
	$(CC) -o L3T5 L3T5.c $(CFLAGS)

clean:
	rm -rfv L3T1 L3T2 L3T3 L3T4 L3T5
