CC = gcc
CFLAGS = -std=c99 -Wall

default: L2T5

all: L2T1 L2T2 L2T3 L2T4 L2T5 

L2T1: L2T1.c
	$(CC) -o L2T1 L2T1.c $(CFLAGS)

L2T2: L2T2.c
	$(CC) -o L2T2 L2T2.c $(CFLAGS)

L2T3: L2T3.c
	$(CC) -o L2T3 L2T3.c $(CFLAGS)

L2T4: L2T4.c
	$(CC) -o L2T4 L2T4.c $(CFLAGS)

L2T5: L2T5.c
	$(CC) -o L2T5 L2T5.c $(CFLAGS)

clean:
	rm -rfv L2T1 L2T2 L2T3 L2T4 L2T5
